import img1 from './assets/arabicDesignImages/1.jpeg'
import img2 from './assets/arabicDesignImages/2.jpeg'
import img3 from './assets/arabicDesignImages/3.jpeg'
import img4 from './assets/arabicDesignImages/4.jpeg'
import img5 from './assets/arabicDesignImages/5.jpeg'
import img6 from './assets/arabicDesignImages/6.jpeg'
import img7 from './assets/arabicDesignImages/7.jpeg'
import img8 from './assets/arabicDesignImages/8.jpeg'
import img9 from './assets/arabicDesignImages/9.jpeg'
import img10 from './assets/arabicDesignImages/10.jpeg'
export {img1,img2,img3,img4,img5,img6,img7,img8,img9,img10}